### ISSUE TITLE
Got errors when doing simple grep `:Agrep -r 'word' ~/dir`

### ISSUE THREAD

**Issue by heshiyou** [ramele/agrep#1] opened 2017-01-24 08:54 UTC
Error detected while processing function Agrep[36]..<SNR>45_set_window[12]..<SNR>45_open_window:
line    1:
E121: Undefined variable: s:bufnr
E116: Invalid arguments for function bufwinnr(s:bufnr)
E15: Invalid expression: bufwinnr(s:bufnr)
line    2:
E121: Undefined variable: winnr
E15: Invalid expression: winnr > 0
Error detected while processing function Agrep:
line   48:
E121: Undefined variable: s:bufnr
E116: Invalid arguments for function job_start(['/bin/bash', '-c', grep_cmd], { 'out_io': 'buffer', 'out_buf': s:bufnr, 'out_modifiable': 0, 'out_cb': function('s:out_cb'), 'close_c
b': function('s:close_cb')})
E15: Invalid expression: job_start(['/bin/bash', '-c', grep_cmd], { 'out_io': 'buffer', 'out_buf': s:bufnr, 'out_modifiable': 0, 'out_cb': function('s:out_cb'), 'close_cb': function
('s:close_cb')})

**Comment by ramele** [comment] 2017-01-26 09:42
Please describe the exact steps to reproduce the issue.
Which Vim version? platform?

**Comment by heshiyou** [comment] 2017-01-27 06:05
vim 8.0，macOS 10.12.3

**Comment by veelenga** [comment] 2017-03-07 15:35
Having exactly the same issue after vim upgrade on Mac OS :/

**Comment by ramele** [comment] 2017-03-07 17:03
What do you mean by "simple grep"? Do you see this issue also when starting vim and :Agrep right after?
Can you see this issue when starting vim as follows?

gvim -N -u NONE -c "syntax on | set rtp+=-path to agrep dir- | so -path to agrep dir-/plugin/agrep.vim"

**Comment by veelenga** [comment] 2017-03-07 17:22
> What do you mean by "simple grep"?

I think it means running the command in the title ":Agrep -r 'word' ~/dir". At least that is my case.

> Do you see this issue also when starting vim and :Agrep right after?

Yes i do.

> Can you see this issue when starting vim as follows?

> gvim -N -u NONE -c "syntax on | set rtp+=-path to agrep dir- | so -path to agrep dir-/plugin/agrep.vim"

No.

Actually i found that the error is gone once i disable [mhinz/vim-startify](https://github.com/mhinz/vim-startify). Can you approve this and suggest how to use both plugins ?

**Comment by ramele** [comment] 2017-03-08 10:28
I don't see any issue with this plugin, at least on Linux but I've just
committed a small fix, please try it and see if it helps.
Also, can you run :ls! after starting vim and see if there is a buffer
named *agrep* there?

**Comment by veelenga** [comment] 2017-03-09 09:02
Hey. Your fix works for me. Thanks a lot.

There is no *agrep* buffer until i run agrep:

![image](https://cloud.githubusercontent.com/assets/3624712/23743004/b7ef1666-04b7-11e7-87dd-67a1414e6fb4.png)

![image](https://cloud.githubusercontent.com/assets/3624712/23743011/bbb5bd7c-04b7-11e7-84ea-db55de0a14c6.png)

I believe it is expected.

**Comment by ramele** [comment] 2017-03-10 22:10
I'm glad it worked for you, but based on your :ls results I'm not sure how...

**Closed as completed** 2017-03-10 22:11 UTC
